In [ ]:
!pip install pandasql

Requirement already satisfied: pandasql in /usr/local/lib/python3.10/dist-packages (0.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.35)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)

In [ ]:
# загрузка нужных библиотек
from io import BytesIO
import requests
import pandas as pd
import pandasql as ps

# убирает ограничение по демонстрации колонок
pd.set_option('display.max_columns', None)

In [ ]:
# создание функции для загрузки таблиц с Google Sheets

def google(spreadsheet_id, sheet_name):

    file_name = (
        'https://docs.google.com/spreadsheets/d/{}/export?format=xlsx'
        .format(spreadsheet_id)
        )
    r = requests.get(file_name)
    df = pd.read_excel(BytesIO(r.content), sheet_name=sheet_name)

    return df

In [ ]:
# чтение данных и запись в переменные
report_offer = google('1jTXLH6jNiPOgm6tArgdGU8oQ86rgHUe-HkVTNp8JiUQ', 'ReportOffer')
buyer = google('1jTXLH6jNiPOgm6tArgdGU8oQ86rgHUe-HkVTNp8JiUQ', 'Buyer')
offer = google('1jTXLH6jNiPOgm6tArgdGU8oQ86rgHUe-HkVTNp8JiUQ', 'Offer')
offer_conv_target = google('1jTXLH6jNiPOgm6tArgdGU8oQ86rgHUe-HkVTNp8JiUQ', 'OfferConversionTarget')
conv_target = google('1jTXLH6jNiPOgm6tArgdGU8oQ86rgHUe-HkVTNp8JiUQ', 'ConversionTarget')

In [ ]:
# создание функции для первичного обзора данных

def first_check(data):

    print('Первые 10 строк таблицы \n')
    display(data.head(10))

    print('-' * 50)
    print('Последние 10 строк таблицы \n')
    display(data.tail(10))

    print('-' * 50)
    print('Информация о таблице \n')
    print(data.info())

    print('-' * 50)
    print('Количество дубликатов:', data.duplicated().sum())

In [ ]:
# первичный обзор данных
first_check(report_offer)

Первые 10 строк таблицы

,id,offer_id,buyer_id,keitaro_stream_id,keitaro_application_id,date,imp_count,proxy_index,click_count,deposit,traffic_cost,traffic_cost_currency,payout_count,commission,developer_revenue,developer_revenue_currency,payout,conversion,confirmed_conversion,payout_currency,latest,remote_service,created_at,updated_at,platform,country,facebook_business_manager_commision,new_campaign,traffic_source,active_campaign,count_new_adset,retargeting,corrected_payout,corrected_conversion,cabinet_id,sub_id,arrival_date,installs,rebill
0,112815907713675463,134505655921533784,121846840494012660,NaN,2.288354e+17,2024-04-10,12877,55e8ae40d3d12310a574acfb8104be42,7669,13,0.000000,RUB,1,0,NaN,Undefined,12180.34857,13,13,RUB,1,Appsflyer,2024-04-10 04:04:21,2024-04-26 13:09:07,ios,RO,0,0,traffic1,0,0,0,12180.34857,13,200615222893464063,NaN,2024-04-10,0,0
1,120225213573077657,134505655921533784,121846840494012660,NaN,2.288354e+17,2024-04-02,3288,103ad1709802cd00d5750c6218a0c8bd,133,0,7360.239150,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-02 12:11:17,2024-04-26 11:02:08,ios,RO,0,0,traffic1,1,0,0,0.00000,0,149072999030963574,NaN,2024-04-02,0,0
2,127456989559006938,134505655921533784,121846840494012660,NaN,2.288354e+17,2024-04-22,6069,103ad1709802cd00d5750c6218a0c8bd,271,0,12194.037450,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-22 02:39:49,2024-04-26 13:10:11,ios,RO,0,0,traffic1,1,0,0,0.00000,0,149072999030963574,NaN,2024-04-22,0,0
3,127456989559010770,134505655921533784,291120475713808723,NaN,2.288354e+17,2024-04-22,1898,a3cd62a26296d3b2363f13c3d09c8dd9,43,0,635.398120,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-22 02:39:49,2024-04-26 13:10:11,ios,RO,0,0,traffic1,1,0,0,0.00000,0,189098836161057493,NaN,2024-04-22,0,0
4,127456989559013577,134505655921533784,225992071264118592,NaN,2.288354e+17,2024-04-22,5733,754578893ef6cbed8f1263511c94ca55,188,0,9110.487750,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-22 02:39:49,2024-04-26 13:10:12,ios,RO,0,0,traffic1,1,0,0,0.00000,0,195759175945262508,NaN,2024-04-22,0,0
5,130976899899429425,134505655921533784,121846840494012660,NaN,2.288354e+17,2024-04-21,7050,103ad1709802cd00d5750c6218a0c8bd,354,0,10161.697875,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-21 02:54:43,2024-04-26 13:10:08,ios,RO,0,0,traffic1,1,0,0,0.00000,0,149072999030963574,NaN,2024-04-21,0,0
6,130976899899434352,134505655921533784,291120475713808723,NaN,2.288354e+17,2024-04-21,1934,a3cd62a26296d3b2363f13c3d09c8dd9,61,0,1906.194360,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-21 02:54:43,2024-04-26 13:10:08,ios,RO,0,0,traffic1,1,0,0,0.00000,0,189098836161057493,NaN,2024-04-21,0,0
7,130976899899442265,134505655921533784,225992071264118592,NaN,2.288354e+17,2024-04-21,6169,754578893ef6cbed8f1263511c94ca55,192,0,6073.658500,RUB,1,0,NaN,Undefined,0.00000,0,0,RUB,1,UnityAds,2024-04-21 02:54:43,2024-04-26 13:10:08,ios,RO,0,0,traffic1,1,0,0,0.00000,0,195759175945262508,NaN,2024-04-21,0,0
8,131306090881835607,134505655921533784,291120475713808723,NaN,2.288354e+17,2024-04-12,3754,c8477f6c362e3c886ec08bfb9f912a0a,2300,1,0.000000,RUB,1,0,NaN,Undefined,936.31749,1,1,RUB,1,Appsflyer,2024-04-12 04:35:43,2024-04-26 13:03:45,ios,RO,0,0,traffic1,0,0,0,936.31749,1,102946705266193470,NaN,2024-04-12,0,0
9,131306090881837951,134505655921533784,225992071264118592,NaN,2.288354e+17,2024-04-12,11892,510c4dcd440293bec1d78a585b3d645b,7139,10,0.000000,RUB,1,0,NaN,Undefined,9363.17490,10,10,RUB,1,Appsflyer,2024-04-12 04:35:43,2024-04-26 13:03:45,ios,RO,0,0,traffic1,0,0,0,9363.17490,10,102946705266193470,NaN,2024-04-12,0,0

--------------------------------------------------
Последние 10 строк таблицы

,id,offer_id,buyer_id,keitaro_stream_id,keitaro_application_id,date,imp_count,proxy_index,click_count,deposit,traffic_cost,traffic_cost_currency,payout_count,commission,developer_revenue,developer_revenue_currency,payout,conversion,confirmed_conversion,payout_currency,latest,remote_service,created_at,updated_at,platform,country,facebook_business_manager_commision,new_campaign,traffic_source,active_campaign,count_new_adset,retargeting,corrected_payout,corrected_conversion,cabinet_id,sub_id,arrival_date,installs,rebill
550,763045545279892343,285976660953456,2316107485700666,NaN,NaN,2024-04-06,172239,002e08cd9460637fdbba6f2060154c53,12967,0,14401.251424,RUB,1,0,NaN,Undefined,16561.439138,0,0,RUB,1,Moloco,2024-04-06 04:03:37,2024-04-26 08:26:23,android,RU,0,0,traffic5,1,0,0,16561.439138,0,246621972818060019,NaN,2024-04-06,0,0
551,817706804212173566,285976660953456,2316107485700666,NaN,NaN,2024-04-20,509722,de29958a4d05ed81d53396351ad529c7,12558,0,0.000000,RUB,1,0,NaN,Undefined,0.000000,0,0,RUB,1,Appsflyer,2024-04-20 01:33:48,2024-04-26 13:02:23,android,RU,0,0,traffic5,0,0,0,0.000000,0,941641081917601573,NaN,2024-04-20,4,0
552,819845726472690497,285976660953456,2316107485700666,NaN,NaN,2024-04-08,383127,002e08cd9460637fdbba6f2060154c53,9913,0,11869.192216,RUB,1,0,NaN,Undefined,13649.571049,0,0,RUB,1,Moloco,2024-04-08 04:03:36,2024-04-26 08:26:49,android,RU,0,0,traffic5,1,0,0,13649.571049,0,246621972818060019,NaN,2024-04-08,0,0
553,919466994802549352,285976660953456,2316107485700666,NaN,NaN,2024-04-22,514769,002e08cd9460637fdbba6f2060154c53,8135,0,13262.000943,RUB,1,0,NaN,Undefined,15251.301084,0,0,RUB,1,Moloco,2024-04-22 04:03:09,2024-04-26 08:29:15,android,RU,0,0,traffic5,1,0,0,15251.301084,0,246621972818060019,NaN,2024-04-22,0,0
554,929326723023503634,285976660953456,2316107485700666,NaN,NaN,2024-04-19,533824,002e08cd9460637fdbba6f2060154c53,10434,0,15286.090175,RUB,1,0,NaN,Undefined,17579.003701,0,0,RUB,1,Moloco,2024-04-19 04:03:21,2024-04-26 08:28:47,android,RU,0,0,traffic5,1,0,0,17579.003701,0,246621972818060019,NaN,2024-04-19,0,0
555,951355817052941039,285976660953456,2316107485700666,NaN,NaN,2024-04-09,554952,002e08cd9460637fdbba6f2060154c53,10322,0,14206.234346,RUB,1,0,NaN,Undefined,16337.169498,0,0,RUB,1,Moloco,2024-04-09 04:03:20,2024-04-26 08:27:01,android,RU,0,0,traffic5,1,0,0,16337.169498,0,246621972818060019,NaN,2024-04-09,0,0
556,990076451227880384,285976660953456,2316107485700666,NaN,NaN,2024-04-16,742449,002e08cd9460637fdbba6f2060154c53,6249,0,13044.977767,RUB,1,0,NaN,Undefined,15001.724432,0,0,RUB,1,Moloco,2024-04-16 04:03:16,2024-04-26 08:28:19,android,RU,0,0,traffic5,1,0,0,15001.724432,0,246621972818060019,NaN,2024-04-16,1,0
557,186696855196155392,306163570818223195,186708678207062663,NaN,2.288354e+17,2024-04-20,0,558fb3ab8f35e9b3ccd77db5249b1792,1,0,0.000000,RUB,1,0,NaN,Undefined,0.000000,0,0,RUB,1,Appsflyer,2024-04-20 15:04:10,2024-04-26 13:02:12,ios,RU,0,0,traffic6,0,0,0,0.000000,0,94164108191760096,NaN,2024-04-20,0,0
558,100507331688008504,697805270138137442,186708678207062663,NaN,2.288354e+17,2024-04-25,0,67255d27825daee8390463e862e8c08e,1,0,0.000000,RUB,1,0,NaN,Undefined,0.000000,0,0,RUB,1,Appsflyer,2024-04-25 21:17:48,2024-04-26 13:17:02,ios,RU,0,0,NaN,0,0,0,0.000000,0,94164108191760096,NaN,2024-04-25,0,0
559,174535582106176439,697805270138137442,186708678207062663,NaN,2.288354e+17,2024-04-06,0,67255d27825daee8390463e862e8c08e,1,0,0.000000,RUB,1,0,NaN,Undefined,0.000000,0,0,RUB,1,Appsflyer,2024-04-06 13:48:57,2024-04-26 13:12:51,ios,RU,0,0,NaN,0,0,0,0.000000,0,94164108191760096,NaN,2024-04-06,0,0

--------------------------------------------------
Информация о таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 39 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id                                   560 non-null    int64
 1   offer_id                             560 non-null    int64
 2   buyer_id                             560 non-null    int64
 3   keitaro_stream_id                    0 non-null      float64
 4   keitaro_application_id               508 non-null    float64
 5   date                                 560 non-null    datetime64[ns]
 6   imp_count                            560 non-null    int64
 7   proxy_index                          560 non-null    object
 8   click_count                          560 non-null    int64
 9   deposit                              560 non-null    int64
 10  traffic_cost                         560 non-null    float64
 11  traffic_cost_currency                560 non-null    object
 12  payout_count                         560 non-null    int64
 13  commission                           560 non-null    int64
 14  developer_revenue                    0 non-null      float64
 15  developer_revenue_currency           560 non-null    object
 16  payout                               560 non-null    float64
 17  conversion                           560 non-null    int64
 18  confirmed_conversion                 560 non-null    int64
 19  payout_currency                      560 non-null    object
 20  latest                               560 non-null    int64
 21  remote_service                       560 non-null    object
 22  created_at                           560 non-null    datetime64[ns]
 23  updated_at                           560 non-null    datetime64[ns]
 24  platform                             560 non-null    object
 25  country                              560 non-null    object
 26  facebook_business_manager_commision  560 non-null    int64
 27  new_campaign                         560 non-null    int64
 28  traffic_source                       555 non-null    object
 29  active_campaign                      560 non-null    int64
 30  count_new_adset                      560 non-null    int64
 31  retargeting                          560 non-null    int64
 32  corrected_payout                     560 non-null    float64
 33  corrected_conversion                 560 non-null    int64
 34  cabinet_id                           560 non-null    int64
 35  sub_id                               0 non-null      float64
 36  arrival_date                         560 non-null    datetime64[ns]
 37  installs                             560 non-null    int64
 38  rebill                               560 non-null    int64
dtypes: datetime64[ns](4), float64(7), int64(20), object(8)
memory usage: 170.8+ KB
None
--------------------------------------------------
Количество дубликатов: 0

In [ ]:
# первичный обзор данных
first_check(buyer)

Первые 10 строк таблицы

,id,name,email,hasoffers_id,created_at,updated_at,team_id,user_id,active,unit_id
0,121846840494012660,Ацуши Сакурай,email455@gmail.com,230,2021-04-12 16:13:18,2021-04-12 16:13:57,193500765377306133,220106840535166937,1,1.404154e+17
1,121846840494012660,Ацуши Сакурай,email455@gmail.com,230,2021-04-12 16:13:18,2021-04-12 16:13:57,193500765377306133,220106840535166937,1,1.404154e+17
2,121846840494012660,Ацуши Сакурай,email455@gmail.com,230,2021-04-12 16:13:18,2021-04-12 16:13:57,193500765377306133,220106840535166937,1,1.404154e+17
3,291120475713808723,Emperor Palpatine,email155@gmail.com,236,2021-12-29 13:25:00,2021-12-29 14:03:44,193500765377306133,769900475594926180,1,NaN
4,225992071264118592,John Doe,email156@gmail.com,263,2022-05-06 13:11:18,2022-05-06 13:12:22,193500765377306133,295252071143466390,1,NaN
5,121846840494012660,Ацуши Сакурай,email455@gmail.com,230,2021-04-12 16:13:18,2021-04-12 16:13:57,193500765377306133,220106840535166937,1,1.404154e+17
6,291120475713808723,Emperor Palpatine,email155@gmail.com,236,2021-12-29 13:25:00,2021-12-29 14:03:44,193500765377306133,769900475594926180,1,NaN
7,225992071264118592,John Doe,email156@gmail.com,263,2022-05-06 13:11:18,2022-05-06 13:12:22,193500765377306133,295252071143466390,1,NaN
8,291120475713808723,Emperor Palpatine,email155@gmail.com,236,2021-12-29 13:25:00,2021-12-29 14:03:44,193500765377306133,769900475594926180,1,NaN
9,225992071264118592,John Doe,email156@gmail.com,263,2022-05-06 13:11:18,2022-05-06 13:12:22,193500765377306133,295252071143466390,1,NaN

--------------------------------------------------
Последние 10 строк таблицы

,id,name,email,hasoffers_id,created_at,updated_at,team_id,user_id,active,unit_id
550,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
551,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
552,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
553,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
554,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
555,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
556,2316107485700666,name_557_surname,email557@gmail.com,243,2022-11-28 16:59:05,2022-11-28 17:05:14,186809663384503219,185980748955837600,1,1.668754e+17
557,186708678207062663,Default Buyer,email560@gmail.com,DefaultBuyer,2018-08-13 13:11:29,2018-09-05 14:26:04,180500766445750793,190007614986252561,1,NaN
558,186708678207062663,Default Buyer,email560@gmail.com,DefaultBuyer,2018-08-13 13:11:29,2018-09-05 14:26:04,180500766445750793,190007614986252561,1,NaN
559,186708678207062663,Default Buyer,email560@gmail.com,DefaultBuyer,2018-08-13 13:11:29,2018-09-05 14:26:04,180500766445750793,190007614986252561,1,NaN

--------------------------------------------------
Информация о таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            560 non-null    int64
 1   name          560 non-null    object
 2   email         560 non-null    object
 3   hasoffers_id  560 non-null    object
 4   created_at    560 non-null    datetime64[ns]
 5   updated_at    560 non-null    datetime64[ns]
 6   team_id       560 non-null    int64
 7   user_id       560 non-null    int64
 8   active        560 non-null    int64
 9   unit_id       361 non-null    float64
dtypes: datetime64[ns](2), float64(1), int64(4), object(3)
memory usage: 43.9+ KB
None
--------------------------------------------------
Количество дубликатов: 547

In [ ]:
# первичный обзор данных
first_check(offer)

Первые 10 строк таблицы

,id,title,tracker,external_id,link,created_at,updated_at,currency,application_external_id,manual,offer_client_id,created_by,appsflyer_retarget,responsible_manager_id,sales_manager_id,team_id,status,paused_at_beginning_month,app_name,comment,total_cap_percent,report_by_registration_date,min_dep,baseline,postback,account_manager_team_id,offer_interaction
0,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_455_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
1,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_455_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
2,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_455_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
3,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_155_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
4,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_156_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
5,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_455_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
6,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_155_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
7,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_156_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
8,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_155_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0
9,134505655921533784,title_208,Appsflyer,6508,www.link_208.com,2022-02-24 17:42:11,2024-03-01 12:17:02,Undefined,252265478585368689,1,1.258626e+17,offer,0,7.179052e+17,1.080336e+17,NaN,Active,0,name_156_surname,comment_462,5.0,0,-,-,-,1.575537e+17,1.0

--------------------------------------------------
Последние 10 строк таблицы

,id,title,tracker,external_id,link,created_at,updated_at,currency,application_external_id,manual,offer_client_id,created_by,appsflyer_retarget,responsible_manager_id,sales_manager_id,team_id,status,paused_at_beginning_month,app_name,comment,total_cap_percent,report_by_registration_date,min_dep,baseline,postback,account_manager_team_id,offer_interaction
550,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
551,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
552,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
553,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
554,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
555,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
556,285976660953456,title_557,Appsflyer,4845,www.link_560.com,2021-05-28 15:38:07,2024-02-19 15:50:31,Undefined,119491001017080464,1,2.800815e+17,offer,0,1.828988e+17,9.354028e+17,NaN,Active,0,name_557_surname,comment_560,0.0,0,-,-,-,1.575537e+17,1.0
557,306163570818223195,title_558,Appsflyer,1039,www.link_560.com,2019-09-02 16:34:36,2020-04-07 17:56:00,Undefined,128271201199941889,1,NaN,offer,0,NaN,NaN,NaN,Stopped,0,name_560_surname,comment_560,NaN,0,NaN,NaN,NaN,NaN,NaN
558,697805270138137442,title_560,Appsflyer,2411,www.link_560.com,2020-08-17 14:01:44,2020-08-17 14:01:44,Undefined,643408010975984552,1,NaN,offer,0,NaN,NaN,NaN,Active,0,name_560_surname,comment_560,NaN,0,NaN,NaN,NaN,NaN,NaN
559,697805270138137442,title_560,Appsflyer,2411,www.link_560.com,2020-08-17 14:01:44,2020-08-17 14:01:44,Undefined,643408010975984552,1,NaN,offer,0,NaN,NaN,NaN,Active,0,name_560_surname,comment_560,NaN,0,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------
Информация о таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           560 non-null    int64
 1   title                        560 non-null    object
 2   tracker                      560 non-null    object
 3   external_id                  560 non-null    int64
 4   link                         560 non-null    object
 5   created_at                   560 non-null    datetime64[ns]
 6   updated_at                   560 non-null    datetime64[ns]
 7   currency                     560 non-null    object
 8   application_external_id      560 non-null    int64
 9   manual                       560 non-null    int64
 10  offer_client_id              554 non-null    float64
 11  created_by                   560 non-null    object
 12  appsflyer_retarget           560 non-null    int64
 13  responsible_manager_id       554 non-null    float64
 14  sales_manager_id             554 non-null    float64
 15  team_id                      0 non-null      float64
 16  status                       560 non-null    object
 17  paused_at_beginning_month    560 non-null    int64
 18  app_name                     560 non-null    object
 19  comment                      560 non-null    object
 20  total_cap_percent            514 non-null    float64
 21  report_by_registration_date  560 non-null    int64
 22  min_dep                      554 non-null    object
 23  baseline                     554 non-null    object
 24  postback                     554 non-null    object
 25  account_manager_team_id      554 non-null    float64
 26  offer_interaction            554 non-null    float64
dtypes: datetime64[ns](2), float64(7), int64(7), object(11)
memory usage: 118.2+ KB
None
--------------------------------------------------
Количество дубликатов: 543

In [ ]:
# первичный обзор данных
first_check(offer_conv_target)

Первые 10 строк таблицы

,id,conversion_target_id,offer_id,paid,currency,cost,created_at,updated_at,date_since,converted,cohort,platform,date_to,country_list,payout_update,retargeting,traffic_source,grab_all_events
0,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,"RO,GE,ES",1,0,UnityAds,0
1,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
2,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
3,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
4,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
5,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,"RO,US,ES",1,0,UnityAds,0
6,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
7,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
8,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0
9,699905390777814791,175106573586007881,134505655921533784,1,EUR,9.3,2024-04-04 11:08:32,2024-04-04 11:08:32,2024-04-01,1,NaN,ios,2024-04-30,RO,1,0,UnityAds,0

--------------------------------------------------
Последние 10 строк таблицы

,id,conversion_target_id,offer_id,paid,currency,cost,created_at,updated_at,date_since,converted,cohort,platform,date_to,country_list,payout_update,retargeting,traffic_source,grab_all_events
550,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
551,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
552,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
553,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
554,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
555,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
556,267035138395784965,674901592770663224,285976660953456,1,USD,15.0,2024-04-01 16:16:59,2024-04-02 10:58:12,2024-04-01,1,NaN,android,2024-04-30,RU,1,0,Moloco,0
557,306163570818395324,175106573586007881,306163570818223195,1,USD,0.3,2019-09-02 16:34:36,2019-09-02 16:37:36,2019-09-01,1,NaN,ios,NaT,Undefined,0,0,Undefined,0
558,610305270094741222,175106573586007881,697805270138137442,1,USD,0.3,2020-08-17 14:01:44,2020-08-17 14:01:44,2020-08-17,1,NaN,Undefined,NaT,RU,1,0,Undefined,0
559,610305270094741222,175106573586007881,697805270138137442,1,USD,0.3,2020-08-17 14:01:44,2020-08-17 14:01:44,2020-08-17,1,NaN,Undefined,NaT,RU,1,0,Undefined,0

--------------------------------------------------
Информация о таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    560 non-null    int64
 1   conversion_target_id  560 non-null    int64
 2   offer_id              560 non-null    int64
 3   paid                  560 non-null    int64
 4   currency              560 non-null    object
 5   cost                  560 non-null    float64
 6   created_at            560 non-null    datetime64[ns]
 7   updated_at            560 non-null    datetime64[ns]
 8   date_since            560 non-null    datetime64[ns]
 9   converted             560 non-null    int64
 10  cohort                0 non-null      float64
 11  platform              560 non-null    object
 12  date_to               514 non-null    datetime64[ns]
 13  country_list          560 non-null    object
 14  payout_update         560 non-null    int64
 15  retargeting           560 non-null    int64
 16  traffic_source        560 non-null    object
 17  grab_all_events       560 non-null    int64
dtypes: datetime64[ns](4), float64(2), int64(8), object(4)
memory usage: 78.9+ KB
None
--------------------------------------------------
Количество дубликатов: 544

In [ ]:
# первичный обзор данных
first_check(conv_target)

Первые 10 строк таблицы

,id,name,code,created_at,updated_at,type,remote_service
0,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
1,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
2,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
3,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
4,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
5,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
6,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
7,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
8,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
9,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer

--------------------------------------------------
Последние 10 строк таблицы

,id,name,code,created_at,updated_at,type,remote_service
550,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
551,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
552,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
553,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
554,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
555,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
556,674901592770663224,Комиссия за спенд,moloco_traffic,2024-02-22 13:00:10,2024-02-22 13:00:32,ByTrafficCost,Moloco
557,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
558,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer
559,175106573586007881,Установка мобильных приложений (Appsflyer),installs,2018-11-08 16:45:09,2018-11-08 16:45:23,ByCode,Appsflyer

--------------------------------------------------
Информация о таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              560 non-null    int64
 1   name            560 non-null    object
 2   code            560 non-null    object
 3   created_at      560 non-null    datetime64[ns]
 4   updated_at      560 non-null    datetime64[ns]
 5   type            560 non-null    object
 6   remote_service  560 non-null    object
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 30.8+ KB
None
--------------------------------------------------
Количество дубликатов: 557

**FYI (disclaimer)**

1. Для компенсации невозможности объединения таблиц ReportOffer и OfferConversionTarget по полю traffic_source, для каждого offer_id была отобрана кампания с наибольшей длительностью, чтобы избежать дубликатов, поскольку длительность кампании как раз отличается источником трафика в поле traffic_source.

2. По аналогичной причине не использовалось поле cost из OfferConversionTarget, поскольку оно завязано на поле traffic_source. Если его использовать, то образуются ненужные дубликаты. Если бы его можно было использовать, то был бы осуществлён перевод валюты в рубли и данная сумма использовалась бы в качестве затрат.

3. В поле platform таблицы OfferConversionTarget есть значение 'Undefined' аналогичное тому, что есть в поле country_list. Поскольку в задании говорилось только про то, что страна Undefined связывается с любой страной, к platform такое условие не применялась и замена значения 'Undefined' не производилась.

4. Поскольку нет описания того, какие поля являются доходом, а какие - расходом, то поле traffic_cost из ReportOffer использовалось как расходы, а поле payout - как доходы.

In [ ]:
query = '''
    WITH oft AS ( -- сбор информации об офферах
                SELECT *,
                        -- определение продолжительности кампании для удаления дубликатов
                        julianday(date_to) - julianday(date_since) AS diff

                FROM ( SELECT DISTINCT
                              o.id,
                              o.title,
                              o.tracker,
                              o.external_id,
                              date(ot.date_since) AS date_since,

                              -- заполнение пустот date_to текущей датой
                              CASE
                                  WHEN date_to IS NULL THEN date('now')
                                  ELSE date(ot.date_to)
                              END AS date_to,

                              ot.platform,
                              ot.country_list,

                              -- замена страны 'Undefined' на список стран, которые упоминаются в report_offer
                              CASE
                                  WHEN ot.country_list = 'Undefined' THEN (SELECT GROUP_CONCAT(DISTINCT country) FROM report_offer)
                                  ELSE ot.country_list
                              END AS country_raw

                      FROM offer AS o

                      INNER JOIN (SELECT DISTINCT * FROM offer_conv_target) AS ot
                      ON o.id = ot.offer_id

                      INNER JOIN (SELECT DISTINCT * FROM conv_target) AS ct
                      ON ot.conversion_target_id = ct.id
                      AND ct.code IN ('installs', 'is_traffic')

                      WHERE o.tracker = 'Appsflyer'
                      ) AS oft_raw
                ),

      ctr AS (  -- таблица с максимальной продолжительностью кампаний и списком стран
                -- для каждого offer_id и соответствующей платформы
                SELECT  id,
                        platform,
                        MAX(diff) AS max_diff,
                        GROUP_CONCAT(DISTINCT country_raw) AS country
                  FROM oft
                  GROUP BY 1, 2
                      ),

      o_fin AS ( -- получение таблицы с нужными офферами
                SELECT  DISTINCT
                        oft.id,
                        oft.title,
                        oft.tracker,
                        oft.external_id,
                        oft.date_since,
                        oft.date_to,
                        oft.platform,
                        ctr.country

                FROM oft

                -- удаление лишних кампаний через объединение таблиц
                INNER JOIN ctr
                ON oft.id = ctr.id
                AND oft.platform = ctr.platform
                AND oft.diff = ctr.max_diff
                ),

        b AS (-- убирает дубликаты в buyer через дату последних изменений
                SELECT  DISTINCT
                        id,
                        FIRST_VALUE(buyer_name) OVER(PARTITION BY id ORDER BY updated_at DESC) AS buyer_name

                FROM (SELECT  id,

                              CASE
                                  WHEN name = 'Default Buyer' OR  hasoffers_id = 'DefaultBuyer' THEN 'Ada Lovelace [130]'
                                  ELSE name || ' [' || hasoffers_id || ']'
                              END AS buyer_name,

                              hasoffers_id,
                              updated_at

                      FROM buyer
                ) AS a_raw
              )

        -- объединение всех таблиц и расчёт числовых данных
        SELECT  r.date,
                b.buyer_name,
                o_fin.id AS offer_title,
                o_fin.tracker AS tracker_type,
                o_fin.external_id AS external_offer_id,
                r.country,
                r.platform,
                r.traffic_source,
                SUM(r.payout) AS revenue,
                SUM(r.traffic_cost) AS costs,
                SUM(r.payout - r.traffic_cost) AS margin,
                SUM(r.confirmed_conversion) AS conversion_cnt

        FROM report_offer AS r

        -- добавляет информацию о байерах
        INNER JOIN b
        ON r.buyer_id = b.id

        -- добавляет информацию об офферах
        INNER JOIN o_fin
        ON r.offer_id = o_fin.id
        AND r.date BETWEEN o_fin.date_since AND o_fin.date_to
        AND o_fin.country LIKE '%' || r.country || '%'
        AND r.platform = o_fin.platform

        WHERE DATE(r.date, 'start of month') = '2024-04-01' -- данные за текущий месяц

        GROUP BY 1, 2, 3, 4, 5, 6, 7, 8

        -- убирает строки с нулевой маржой
        HAVING SUM(r.payout - r.traffic_cost) <> 0

    '''
query_res = ps.sqldf(query, locals())

query_res

,date,buyer_name,offer_title,tracker_type,external_offer_id,country,platform,traffic_source,revenue,costs,margin,conversion_cnt
0,2024-04-01 00:00:00.000000,Emperor Palpatine [236],134505655921533784,Appsflyer,6508,RO,ios,traffic1,0.00000,628.08880,-628.08880,0
1,2024-04-01 00:00:00.000000,John Doe [263],134505655921533784,Appsflyer,6508,RO,ios,traffic1,8330.65263,6003.79000,2326.86263,9
2,2024-04-01 00:00:00.000000,name_461_surname [238],134505655921533784,Appsflyer,6508,RO,ios,traffic2,3981.19600,3879.37200,101.82400,5
3,2024-04-01 00:00:00.000000,name_462_surname [219],138394909325266725,Appsflyer,14769,UA,ios,traffic1,0.00000,559.73796,-559.73796,0
4,2024-04-01 00:00:00.000000,Ацуши Сакурай [230],134505655921533784,Appsflyer,6508,RO,ios,traffic1,7405.02456,4017.92100,3387.10356,8
...,...,...,...,...,...,...,...,...,...,...,...,...
148,2024-04-25 00:00:00.000000,Ацуши Сакурай [230],134505655921533784,Appsflyer,6508,RO,ios,traffic1,11038.55688,8048.00460,2990.55228,12
149,2024-04-26 00:00:00.000000,Emperor Palpatine [236],134505655921533784,Appsflyer,6508,RO,ios,traffic1,917.98347,626.49352,291.48995,1
150,2024-04-26 00:00:00.000000,John Doe [263],134505655921533784,Appsflyer,6508,RO,ios,traffic1,917.98347,0.00000,917.98347,1
151,2024-04-26 00:00:00.000000,name_461_surname [238],134505655921533784,Appsflyer,6508,RO,ios,traffic2,789.66320,644.91980,144.74340,1
152,2024-04-26 00:00:00.000000,Ацуши Сакурай [230],134505655921533784,Appsflyer,6508,RO,ios,traffic1,5507.90082,3339.76325,2168.13757,6